"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

icon = "./resources/fig.ico"
r_path = '/Library/Frameworks/R.framework/Resources/'

r_dependencies = [
    r_path
]

resources = [
    ('resources', r_dependencies),
    ("resources/R_scripts", [
        r"./resources/R_scripts/sensmixedVer4.2.R",
        r"./resources/R_scripts/sensmixedNoRepVer1.1.R"
    ]),
    ("resources/", [
        r"./resources/about.html",
        r"./resources/about.png",
        r"./resources/dtu_logo.png",
        icon,
        r"./resources/help.pdf",
        r"./resources/logo.png",
        r"./resources/nofima_logo.png",
        r"./resources/uoc_logo.png",
        r"./resources/workflow.pdf"
    ]),
    ("resources/gfx", [
        r"./resources/gfx/_pc_circle.gif",
        r"./resources/gfx/_pc_pointer_down.gif",
        r"./resources/gfx/_pc_pointer_up.gif",
        r"./resources/gfx/_pc_pointer_right.gif",
        r"./resources/gfx/_pc_pointer_left.gif",
        r"./resources/gfx/_ctrl_print.gif",
        r"./resources/gfx/_ctrl_print_setup.gif",
        r"./resources/gfx/_ctrl_save.gif",
        r"./resources/gfx/_ctrl_copy.gif",
        r"./resources/gfx/_nav_home.gif",
        r"./resources/gfx/_nav_zoom.gif",
        r"./resources/gfx/_nav_pan.gif"
    ])
]

APP = ['PanelCheck.py']
DATA_FILES = []

OPTIONS = {
    'iconfile': icon,
    'resources': resources
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
